<?php
if ( ! defined( 'ABSPATH' ) ) { exit; }
use Aws\SecretsManager\SecretsManagerClient;

class MRM_Masterclass_Plugin {
const DB_VERSION='1.1.0'; const REST_NAMESPACE='mrm-masterclass/v1';
public static function activate(){self::install_tables(); if(!wp_next_scheduled('mrm_masterclass_send_reminders')) wp_schedule_event(time()+300,'mrm_masterclass_15min','mrm_masterclass_send_reminders');}
public static function deactivate(){wp_clear_scheduled_hook('mrm_masterclass_send_reminders');}
public function __construct(){add_action('init',[$this,'runtime_upgrade']); add_action('rest_api_init',[$this,'register_rest_routes']); add_action('admin_menu',[$this,'register_admin_menu']); add_filter('cron_schedules',[$this,'cron']); add_action('mrm_masterclass_send_reminders',[$this,'send_reminders']); foreach(['mrm_masterclass_save_settings'=>'save_settings','mrm_masterclass_save_presenter'=>'save_presenter','mrm_masterclass_delete_presenter'=>'delete_presenter','mrm_masterclass_save_event'=>'save_event','mrm_masterclass_cancel_event'=>'cancel_event','mrm_masterclass_resend_confirmation'=>'resend_confirmation','mrm_masterclass_resend_reminder'=>'resend_reminder','mrm_masterclass_emergency_cancel_confirm'=>'emergency_confirm','mrm_masterclass_emergency_cancel_execute'=>'emergency_execute'] as $a=>$m){add_action('admin_post_'.$a,[$this,$m]);add_action('admin_post_nopriv_'.$a,[$this,$m]);}}
private function t($n){global $wpdb;return $wpdb->prefix.$n;} private function now(){return gmdate('Y-m-d H:i:s');} private function must_admin(){if(!current_user_can('manage_options')) wp_die('Unauthorized');}
public function runtime_upgrade(){if(get_option('mrm_masterclass_db_version')!==self::DB_VERSION) self::install_tables();}
public static function install_tables(){global $wpdb;require_once ABSPATH.'wp-admin/includes/upgrade.php';$p=$wpdb->prefix;
dbDelta("CREATE TABLE {$p}mrm_masterclass_presenters (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,name VARCHAR(191) NOT NULL,email VARCHAR(191) NOT NULL,bio TEXT NULL,is_active TINYINT(1) NOT NULL DEFAULT 1,is_masterclass_presenter TINYINT(1) NOT NULL DEFAULT 1,imported_instructor_id BIGINT UNSIGNED NULL,google_calendar_id VARCHAR(191) NULL,created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL,KEY email(email));");
dbDelta("CREATE TABLE {$p}mrm_masterclass_events (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,title VARCHAR(191) NOT NULL,description LONGTEXT NULL,presenter_id BIGINT UNSIGNED NULL,presenter_email VARCHAR(191) NULL,calendar_id VARCHAR(191) NULL,google_event_id VARCHAR(191) NULL,google_meet_url TEXT NULL,start_time DATETIME NOT NULL,end_time DATETIME NOT NULL,timezone VARCHAR(64) NOT NULL DEFAULT 'UTC',price_cents INT NOT NULL DEFAULT 2000,capacity INT NOT NULL DEFAULT 100,status VARCHAR(32) NOT NULL DEFAULT 'draft',registration_open TINYINT(1) NOT NULL DEFAULT 1,terms_version VARCHAR(32) NOT NULL DEFAULT 'v1',created_by_user_id BIGINT UNSIGNED NULL,cancelled_at DATETIME NULL,cancellation_reason TEXT NULL,presenter_reminder_24_sent_at DATETIME NULL,presenter_reminder_1_sent_at DATETIME NULL,created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL,KEY start_time(start_time));");
dbDelta("CREATE TABLE {$p}mrm_masterclass_registrations (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,event_id BIGINT UNSIGNED NOT NULL,first_name VARCHAR(191) NOT NULL,last_name VARCHAR(191) NOT NULL,email VARCHAR(191) NOT NULL,email_hash VARCHAR(64) NOT NULL,phone VARCHAR(64) NULL,stripe_payment_intent_id VARCHAR(191) NOT NULL,stripe_customer_id VARCHAR(191) NULL,amount_cents INT NOT NULL,currency VARCHAR(10) NOT NULL DEFAULT 'usd',payment_status VARCHAR(32) NOT NULL DEFAULT 'pending',google_attendee_added TINYINT(1) NOT NULL DEFAULT 0,google_attendee_error TEXT NULL,confirmation_sent_at DATETIME NULL,reminder_24_sent_at DATETIME NULL,reminder_1_sent_at DATETIME NULL,cancelled_at DATETIME NULL,refunded_at DATETIME NULL,refund_status VARCHAR(32) NULL,terms_version VARCHAR(32) NOT NULL,terms_accepted TINYINT(1) NOT NULL DEFAULT 0,ip_address VARCHAR(100) NULL,user_agent TEXT NULL,created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL,KEY event_id(event_id),UNIQUE KEY pi_unique(stripe_payment_intent_id));");
dbDelta("CREATE TABLE {$p}mrm_masterclass_refunds (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,registration_id BIGINT UNSIGNED NOT NULL,event_id BIGINT UNSIGNED NOT NULL,stripe_refund_id VARCHAR(191) NULL,stripe_payment_intent_id VARCHAR(191) NOT NULL,amount_cents INT NOT NULL,status VARCHAR(32) NOT NULL,error_message TEXT NULL,notes TEXT NULL,created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL);");
dbDelta("CREATE TABLE {$p}mrm_masterclass_email_log (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,event_id BIGINT UNSIGNED NULL,registration_id BIGINT UNSIGNED NULL,recipient_email VARCHAR(191) NOT NULL,email_type VARCHAR(64) NOT NULL,subject VARCHAR(255) NOT NULL,status VARCHAR(32) NOT NULL,error_message TEXT NULL,sent_at DATETIME NOT NULL);");
dbDelta("CREATE TABLE {$p}mrm_masterclass_unmute_requests (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,event_id BIGINT UNSIGNED NOT NULL,registration_id BIGINT UNSIGNED NULL,participant_name VARCHAR(191) NOT NULL,participant_email VARCHAR(191) NOT NULL,request_note TEXT NULL,status VARCHAR(32) NOT NULL DEFAULT 'pending',presenter_response TEXT NULL,responded_at DATETIME NULL,created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL);"); update_option('mrm_masterclass_db_version',self::DB_VERSION);}
public function cron($s){$s['mrm_masterclass_15min']=['interval'=>900,'display'=>'Masterclass 15m'];return $s;}
private function settings(){return wp_parse_args(get_option('mrm_masterclass_settings',[]),['masterclass_calendar_id'=>'','default_price_cents'=>2000,'default_capacity'=>100,'default_timezone'=>'America/New_York','admin_notification_email'=>get_option('admin_email'),'from_email'=>'no-reply@lowbrass-lessons.com','terms_version'=>'v1','participant_reminder_24_enabled'=>1,'participant_reminder_1_enabled'=>1,'presenter_reminder_24_enabled'=>1,'presenter_reminder_1_enabled'=>1,'google_meet_host_instructions'=>'Use Google Meet Host Controls to manage muting/unmuting.','cancellation_policy_text'=>'If cancelled by presenter, paid attendees are refunded.']);}
private function secret($id){if(!defined('MRM_AWS_REGION')||!defined('MRM_AWS_ACCESS_KEY_ID')||!defined('MRM_AWS_SECRET_ACCESS_KEY')||!class_exists('Aws\SecretsManager\SecretsManagerClient')) return null; try{$c=new SecretsManagerClient(['version'=>'latest','region'=>MRM_AWS_REGION,'credentials'=>['key'=>MRM_AWS_ACCESS_KEY_ID,'secret'=>MRM_AWS_SECRET_ACCESS_KEY]]);$r=$c->getSecretValue(['SecretId'=>$id]);return json_decode((string)($r['SecretString']??''),true);}catch(Exception $e){return null;}}
private function mrm_mc_get_google_service_account_json(){ $s=$this->secret('lowbrass/google/scheduler'); return is_array($s)?(is_string($s['service_account_json']??null)?$s['service_account_json']:wp_json_encode($s['service_account_json']??[])):''; }
private function stripe_key($pub=false){$s=$this->secret('lowbrass/stripe/keys'); return is_array($s)?($pub?($s['publishable_key']??''):($s['secret_key']??'')):'';}
private function mrm_mc_google_get_access_token(){ $sa=json_decode($this->mrm_mc_get_google_service_account_json(),true); if(!$sa||empty($sa['private_key'])) return ''; $header=rtrim(strtr(base64_encode(wp_json_encode(['alg'=>'RS256','typ'=>'JWT'])),'+/','-_'),'='); $iat=time(); $claim=rtrim(strtr(base64_encode(wp_json_encode(['iss'=>$sa['client_email'],'scope'=>'https://www.googleapis.com/auth/calendar','aud'=>'https://oauth2.googleapis.com/token','iat'=>$iat,'exp'=>$iat+3600])),'+/','-_'),'='); openssl_sign($header.'.'.$claim,$sig,$sa['private_key'],'sha256'); $jwt=$header.'.'.$claim.'.'.rtrim(strtr(base64_encode($sig),'+/','-_'),'='); $res=wp_remote_post('https://oauth2.googleapis.com/token',['body'=>['grant_type'=>'urn:ietf:params:oauth:grant-type:jwt-bearer','assertion'=>$jwt]]); $b=json_decode(wp_remote_retrieve_body($res),true); return $b['access_token']??''; }
private function mrm_mc_google_request($method,$path,$body=null){$t=$this->mrm_mc_google_get_access_token(); if(!$t) return new WP_Error('google_auth','No token'); $args=['method'=>$method,'headers'=>['Authorization'=>'Bearer '.$t,'Content-Type'=>'application/json']]; if($body)$args['body']=wp_json_encode($body); $r=wp_remote_request('https://www.googleapis.com/calendar/v3/'.$path,$args); if(is_wp_error($r)) return $r; return json_decode(wp_remote_retrieve_body($r),true);}
private function mrm_mc_google_insert_event($event,$presenter_email){$s=$this->settings(); $cal=$s['masterclass_calendar_id']?:'primary'; $payload=['summary'=>$event['title'],'description'=>$event['description'],'start'=>['dateTime'=>gmdate('c',strtotime($event['start_time'])),'timeZone'=>$event['timezone']],'end'=>['dateTime'=>gmdate('c',strtotime($event['end_time'])),'timeZone'=>$event['timezone']],'attendees'=>$presenter_email?[['email'=>$presenter_email]]:[],'conferenceData'=>['createRequest'=>['requestId'=>'mrm_mc_'.$event['id'].'_'.time(),'conferenceSolutionKey'=>['type'=>'hangoutsMeet']]]]; $res=$this->mrm_mc_google_request('POST','calendars/'.rawurlencode($cal).'/events?conferenceDataVersion=1&sendUpdates=all',$payload); return ['google_event_id'=>$res['id']??'','google_meet_url'=>$this->mrm_mc_extract_meet_url($res),'calendar_id'=>$cal];}
private function mrm_mc_extract_meet_url($e){foreach(($e['conferenceData']['entryPoints']??[]) as $ep){if(($ep['entryPointType']??'')==='video') return $ep['uri']??'';} return $e['hangoutLink']??'';}
private function mrm_mc_google_patch_event_attendees($event,$emails){$att=[]; foreach(array_unique(array_filter($emails)) as $em){$att[]=['email'=>$em];} $res=$this->mrm_mc_google_request('PATCH','calendars/'.rawurlencode($event->calendar_id?:'primary').'/events/'.rawurlencode($event->google_event_id).'?sendUpdates=all',['attendees'=>$att]); return !is_wp_error($res);}
private function mrm_mc_google_cancel_event($event){if(empty($event->google_event_id)) return true; $res=$this->mrm_mc_google_request('PATCH','calendars/'.rawurlencode($event->calendar_id?:'primary').'/events/'.rawurlencode($event->google_event_id).'?sendUpdates=all',['status'=>'cancelled']); return !is_wp_error($res);}
private function stripe_req($m,$ep,$body=[]){$k=$this->stripe_key(); if(!$k) return new WP_Error('stripe','missing'); $args=['method'=>$m,'headers'=>['Authorization'=>'Bearer '.$k,'Content-Type'=>'application/x-www-form-urlencoded']]; if($body)$args['body']=http_build_query($body); $r=wp_remote_request('https://api.stripe.com/v1/'.$ep,$args); if(is_wp_error($r)) return $r; return json_decode(wp_remote_retrieve_body($r),true);}
public function register_admin_menu(){add_menu_page('MRM Masterclass','MRM Masterclass','manage_options','mrm-masterclass',[$this,'events']);add_submenu_page('mrm-masterclass','Events','Events','manage_options','mrm-masterclass',[$this,'events']);add_submenu_page('mrm-masterclass','Presenters','Presenters','manage_options','mrm-masterclass-presenters',[$this,'presenters']);add_submenu_page('mrm-masterclass','Registrations','Registrations','manage_options','mrm-masterclass-registrations',[$this,'registrations']);add_submenu_page('mrm-masterclass','Settings','Settings','manage_options','mrm-masterclass-settings',[$this,'settings_page']);add_submenu_page('mrm-masterclass','Email Log','Email Log','manage_options','mrm-masterclass-email-log',[$this,'email_log']);}
private function notice(){if(!empty($_GET['mrm_notice'])) echo '<div class="notice notice-success"><p>'.esc_html(wp_unslash($_GET['mrm_notice'])).'</p></div>';}
public function events(){global $wpdb;$this->must_admin();$this->notice();$edit=!empty($_GET['edit'])?$wpdb->get_row($wpdb->prepare("SELECT * FROM {$this->t('mrm_masterclass_events')} WHERE id=%d",absint($_GET['edit']))):null;$prs=$wpdb->get_results("SELECT * FROM {$this->t('mrm_masterclass_presenters')} WHERE is_active=1 ORDER BY name");echo '<div class="wrap"><h1>Masterclass Events</h1><form method="post" action="'.esc_url(admin_url('admin-post.php')).'">';wp_nonce_field('mrm_masterclass_save_event');echo '<input type="hidden" name="action" value="mrm_masterclass_save_event"><input type="hidden" name="event_id" value="'.esc_attr($edit->id??0).'"><table class="form-table"><tr><th>Title</th><td><input name="title" class="regular-text" value="'.esc_attr($edit->title??'').'"></td></tr></table><p><button class="button button-primary">Save Event</button></p></form></div>';}
public function presenters(){echo '<div class="wrap"><h1>Presenters</h1></div>';}
public function registrations(){echo '<div class="wrap"><h1>Registrations</h1></div>';}
public function settings_page(){echo '<div class="wrap"><h1>Settings</h1></div>';}
public function email_log(){echo '<div class="wrap"><h1>Email Log</h1></div>';}
public function register_rest_routes(){register_rest_route(self::REST_NAMESPACE,'/events',['methods'=>'GET','callback'=>[$this,'rest_events'],'permission_callback'=>'__return_true']);register_rest_route(self::REST_NAMESPACE,'/event',['methods'=>'GET','callback'=>[$this,'rest_event'],'permission_callback'=>'__return_true']);register_rest_route(self::REST_NAMESPACE,'/create-payment-intent',['methods'=>'POST','callback'=>[$this,'create_pi'],'permission_callback'=>'__return_true']);register_rest_route(self::REST_NAMESPACE,'/verify-payment-intent',['methods'=>'POST','callback'=>[$this,'verify_pi'],'permission_callback'=>'__return_true']);register_rest_route(self::REST_NAMESPACE,'/finalize-registration',['methods'=>'POST','callback'=>[$this,'finalize'],'permission_callback'=>'__return_true']);register_rest_route(self::REST_NAMESPACE,'/unmute-request',['methods'=>'POST','callback'=>[$this,'unmute'],'permission_callback'=>'__return_true']);register_rest_route(self::REST_NAMESPACE,'/presenter/unmute-requests',['methods'=>'GET','callback'=>[$this,'presenter_unmute'],'permission_callback'=>'__return_true']);register_rest_route(self::REST_NAMESPACE,'/presenter/respond-unmute',['methods'=>'POST','callback'=>[$this,'presenter_respond'],'permission_callback'=>'__return_true']);register_rest_route(self::REST_NAMESPACE,'/settings-public',['methods'=>'GET','callback'=>function(){ $s=$this->settings(); return ['stripe_publishable_key'=>$this->stripe_key(true),'terms_version'=>$s['terms_version'],'cancellation_policy_text'=>$s['cancellation_policy_text']]; },'permission_callback'=>'__return_true']);}
public function rest_events(){global $wpdb;return $wpdb->get_results("SELECT e.id,e.title,e.description,p.name presenter_name,e.start_time,e.end_time,e.timezone,e.price_cents,e.capacity,(e.capacity-COALESCE((SELECT COUNT(*) FROM {$this->t('mrm_masterclass_registrations')} r WHERE r.event_id=e.id AND r.payment_status='paid'),0)) available_seats,e.status,e.registration_open FROM {$this->t('mrm_masterclass_events')} e LEFT JOIN {$this->t('mrm_masterclass_presenters')} p ON p.id=e.presenter_id WHERE e.status='scheduled' ORDER BY e.start_time ASC");}
public function rest_event($r){global $wpdb;return $wpdb->get_row($wpdb->prepare("SELECT * FROM {$this->t('mrm_masterclass_events')} WHERE id=%d",absint($r['id'])));}
public function create_pi($r){global $wpdb;$e=$wpdb->get_row($wpdb->prepare("SELECT * FROM {$this->t('mrm_masterclass_events')} WHERE id=%d",absint($r['event_id'])));$terms=$this->settings()['terms_version'];$pi=$this->stripe_req('POST','payment_intents',['amount'=>$e->price_cents,'currency'=>'usd','automatic_payment_methods[enabled]'=>'true','metadata[mrm_masterclass_event_id]'=>$e->id,'metadata[mrm_masterclass_customer_email]'=>sanitize_email($r['email']),'metadata[mrm_product_type]'=>'masterclass','metadata[source_flow]'=>'masterclass_registration','metadata[terms_version]'=>$terms,'metadata[terms_accepted]'=>rest_sanitize_boolean($r['terms_accepted'])?'1':'0']);return ['client_secret'=>$pi['client_secret']??'','publishable_key'=>$this->stripe_key(true)];}
public function verify_pi($r){$pi=$this->stripe_req('GET','payment_intents/'.rawurlencode(sanitize_text_field($r['payment_intent_id'])));return ['status'=>$pi['status']??'unknown'];}
public function finalize($r){return ['ok'=>true];}
public function unmute($r){return ['ok'=>true];}
public function presenter_unmute($r){return [];}
public function presenter_respond($r){return ['ok'=>true];}
public function send_reminders(){}
public function save_settings(){ $this->must_admin(); }
public function save_presenter(){ $this->must_admin(); }
public function delete_presenter(){ $this->must_admin(); }
public function save_event(){ $this->must_admin(); }
public function cancel_event(){ $this->must_admin(); }
public function resend_confirmation(){ $this->must_admin(); }
public function resend_reminder(){ $this->must_admin(); }
private function sign_token($p,$ttl=3600){$p['exp']=time()+$ttl;$raw=wp_json_encode($p);$sig=hash_hmac('sha256',$raw,wp_salt('auth'));return rtrim(strtr(base64_encode($raw.'||'.$sig),'+/','-_'),'=');}
private function verify_token($t){$d=base64_decode(strtr($t,'-_','+/'));if(!$d||strpos($d,'||')===false)return false;[$raw,$sig]=explode('||',$d,2);if(!hash_equals(hash_hmac('sha256',$raw,wp_salt('auth')),$sig))return false;$p=json_decode($raw,true);return (!empty($p['exp'])&&time()<=$p['exp'])?$p:false;}
public function emergency_confirm(){echo 'confirm';exit;} public function emergency_execute(){echo 'done';exit;}
}
function mrm_masterclass_plugin(){static $i=null;if(!$i)$i=new MRM_Masterclass_Plugin();return $i;} 
